### ISSUE TITLE
The "invert_image" parameters on every app's icon is true by default, which it shouldn't be.

### ISSUE THREAD

**Issue by MCAlexisYT** [electrovoyage/electrovoyage-Hammer-Launcher#1]
It seems like that the opaque the transparent parts of the icons have been inverted.
![image](https://github.com/user-attachments/assets/34c51b38-47f0-4d25-9db5-dfe8945657d7)

**Comment by MCAlexisYT** [comment]
Update: the `invert_image` parameters was the culprit. (Seriously, why is that on by default?)

**Comment by electrovoyage** [comment]
> Update: the `invert_image` parameters was the culprit. (Seriously, why is that on by default?)

It's on my default because custom icons require inversion and Valve icons don't. I can fix this for the next release but you will need to delete your sdk.json to let the program regenerate it from your game's launcher's data.

**Comment by electrovoyage** [comment]
Either that or you can manually change the values of every program.

**Comment by electrovoyage** [comment]
Fixed in [new release](https://github.com/TPEcool/electrovoyage-Hammer-Launcher/releases/latest).
