### ISSUE TITLE
My Review

### ISSUE THREAD

**Issue by TheEndQueen** [electrovoyage/electrovoyage-Hammer-Launcher#2]
5/5 stars, very useful.

**Comment by electrovoyage** [comment]
woah, this is worthless

**Comment by TheEndQueen** [comment]
no

**Comment by TheEndQueen** [comment]
It's so useful in fact that I pinned it to my taskbar
![Screenshot 2024-10-05 050555](https://github.com/user-attachments/assets/6bc5810c-c290-44bf-9ec9-c10e235976ea)
